"""PlatformAdapter — abstract interface for all platforms."""
from __future__ import annotations
from abc import ABC, abstractmethod
import numpy as np


class PlatformAdapter(ABC):
    @abstractmethod
    async def capture(self) -> tuple[np.ndarray, dict]: ...
    @abstractmethod
    async def get_ui_tree(self) -> list[dict]: ...
    @abstractmethod
    def get_screen_size(self) -> tuple[int, int]: ...
    @abstractmethod
    async def execute_click(self, x: int, y: int, button: str = "left") -> bool: ...
    @abstractmethod
    async def execute_type(self, text: str) -> bool: ...
    @abstractmethod
    async def execute_scroll(self, x: int, y: int, direction: str, amount: int) -> bool: ...
    @abstractmethod
    async def execute_key(self, key_combo: str) -> bool: ...
